config/routes.rb
Rails.application.routes.draw do

  # Routes For Devise Authentications
  devise_for :accounts, controllers: { 
    registrations: 'accounts/registrations',
    sessions:      'accounts/sessions'
  }
       get 'update_locale/:locale', to: 'application#update_locale', as: :update_locale



  # Asegúrate de que las rutas de devise estén antes de las demás rutas
  namespace :accounts do
    resources :sessions, only: [:index, :create, :destroy]
  end

  # Routes for Public View
  namespace :web, path: '', as: '' do
    root to: 'home#index'
    get 'home/index'
   
    # Otras rutas públicas
    resources :products, only: [:index, :show]
  end

  # Routes for Global Configuration
  namespace :system_management do
    resources :accounts, :languages, :countries, :profiles, :settings, :accesses do
      member do
        get 'delete'
      end
      match 'search',   :via => [:post,:get], :on => :collection      
    end   
  end

  # Routes for Admin View
  namespace :admin_management do
    root to: 'dashboard#index'
    #get 'dashboard/index'
    resources :dashboard, only: [:index]

    # Routes Standar with delete
    resources :profiles, :accounts, :positions, :customers, :employees, :type_payments, :report_payments, :products, :suppliers do
      member do
        get 'delete'
      end
      match 'search',   :via => [:post,:get], :on => :collection
    end
    
    # Routes for Sales with custom actions
    resources :sales do
      member do
        get 'delete'
        get 'cancel_sale'
      end
    end
  end



  
  # Routes for Global Configuration
  namespace :application_management do
    resources :settings do
      member do
        get 'delete'
      end
      match 'search',   :via => [:post,:get], :on => :collection
    end    
  end


end

app/models/profile.rb
class Profile < ApplicationRecord
  # Relatiohships
  has_many :profile_accesses, dependent: :destroy
  has_many :accesses, through: :profile_accesses
  has_many :accounts, dependent: :destroy

  # Validations
  # Important! - Change values according the model
  validates :name, presence: true, uniqueness: { case_sensitive: false, conditions: -> { where(deleted: '0') },
   message: ->(object, data) { I18n.t('activerecord.errors.models.#{model_name.i18n_key}.attributes.name.taken') } }

  # Scopes
  scope :not_deleted, -> { where(deleted: false) }

  # Pagination Kaminari
  paginates_per 10

  # Actions from callbacks
  before_save :save_default_values, :if => :new_record?
  
  # Crate String Active Status for display on view as span
  def active_status
    if active
      '<span class="badge bg-olive">'.html_safe  + I18n.t('standard.active') + '</span>'.html_safe
    else
      '<span class="badge bg-danger">'.html_safe + I18n.t('standard.blocked') + '</span>'.html_safe
    end
  end
  
  # Crate String Active Status for display on view as simple text
  def active_status_text
    if active
      I18n.t('standard.active')
    else
      I18n.t('standard.blocked')
    end
  end
  
  # Sobrecargar full_messages para eliminar el nombre del atributo
  def self.human_attribute_name(attr, options = {})
    ''
  end
  
  # Important! - Change values according the model
  def self.ransackable_attributes(auth_object = nil)
    %w[id name active deleted created_at updated_at]
  end

  # Important! - Change values according the model
  def self.ransackable_associations(auth_object = nil)
    %w[profile_accesses]
  end
  
  # Callbacks
  private
  
  # Set values for new records
  def save_default_values
    self.active  = true 
    self.deleted = false  
  end 

end

app/controllers/admin_management/profiles_controller.rb
module Admin
  class ProfilesController < ApplicationController
    # Autentication
    before_action :authenticate_account!
    before_action -> { authorize!('index', 'Profile') }, only: [:index]
    before_action -> { authorize!('new',   'Profile') }, only: [:new, :create]
    before_action -> { authorize!('show',  'Profile') }, only: [:show]
    before_action -> { authorize!('edit',  'Profile') }, only: [:edit, :update]
    before_action -> { authorize!('delete','Profile') }, only: [:delete, :destroy]

    # call private actions
    before_action :set_default_values
    before_action :set_model, only: [:show, :edit, :update, :destroy, :delete]
    before_action :set_main_form, only: [:new, :create, :edit, :update]
    before_action :set_list_collections, only: [:new, :edit, :create, :update]
   
    # Action Index
    def index
      @list_array = @main_model.includes(image_attachment: :blob).not_deleted
      
      respond_to do |format|
        format.html
        format.js
        format.json
      end
    end
    
    # Action New
    def new
      @action_title = "Nuevo"
      @main_table = @main_model.new   
    end
    
    # Action Create
    def create
      @action_title = "Nuevo"
      @main_table = @main_model.new(model_attributes)

      respond_to do |format|
        if @main_table.save
          format.js
        else
          format.js { render :new }
        end
      end
    end
    
    # Action Show
    def show
      @action_title = "Mostrar"
      @main_form    = 'form_show'
    end
    
    # Action Edit
    def edit
      @action_title = "Editar"
    end
    
    # Action Update
    def update
      @action_title = "Editar"

      respond_to do |format|
        if @main_table.update(model_attributes)
          format.js
        else
          format.js { render :edit }
        end
      end
    end

    # Action Delete
    def delete
      @action_title = "Eliminar"
      @main_form    = 'form_delete'
    end

    # Action Destroy
    def destroy
      @main_table.update(deleted: true, deleted_DESCription: params[@param_model][:deleted_DESCription])
      
      respond_to do |format|
        format.js
      end
    end
    
    # Private actions
    private
    
    def set_default_values
      @main_model  = Profile
      @param_model = :profile
      @main_url    = "/admin/profiles"    
      @title_index = "Pefiles"
      @title_modal = "Perfil"
    end

    def set_main_form
      @main_form    = 'form'
    end

    def set_list_collections
      @accesses = Access.all 
    end

    def set_model
      @main_table = @main_model.find(params[:id])
    end
    
    # Params for model
    def model_attributes
      params.require(@param_model).permit!
    end
  end
end

app/controllers/system_management/profiles_controller.rb
module SystemManagement  # Main Folder
  class ProfilesController < ApplicationController  # Controller Name
    # Autentication
    before_action :authenticate_account!
    
    # Call permissions
    before_action -> { authorize!('index', @main_model) }, only: [:index]
    before_action -> { authorize!('new',   @main_model) }, only: [:new, :create]
    before_action -> { authorize!('show',  @main_model) }, only: [:show]
    before_action -> { authorize!('edit',  @main_model) }, only: [:edit, :update]
    before_action -> { authorize!('delete',@main_model) }, only: [:delete, :destroy]
    
    # Call Private Actions
    before_action :set_model, only: [:show, :edit, :update, :destroy, :delete]
    before_action :set_main_form, only: [:new, :create, :edit, :update]
    before_action :set_list_collections, only: [:new, :edit, :create, :update]

    # Action Search
    # Important! - Change values according the model
    def search      
      permitted_params = params.require(:q).permit(:name_cont, :active_eq)
      redirect_to action: :index, q: permitted_params, format: params[:format]
    end
   
    # Action Index
    def index
      @query = @main_model.ransack(params[:q])

      if request.format.xlsx?
        @list_array = @query.result.not_deleted.order("name DESC")
      else
        @list_array = @query.result.not_deleted.order("name DESC").page(params[:page])
      end
 
      respond_to do |format|
        format.html
        format.json
        format.xlsx { render xlsx: "index", filename: "#{@plural_title}_#{Date.today}.xlsx" }
      end
    end
    
    # Action New
    def new
      @main_table = @main_model.new
    end
    
    # Action Create
    def create
      @main_table = @main_model.new(model_attributes)
      respond_to do |format|
        if @main_table.save
          format.js
        else
          format.js { render :new }
        end
      end
    end
    
    # Action Show
    def show
      @main_form = 'form_show'
    end
    
    # Action Edit
    def edit
    end
    
    # Action Update
    def update
      respond_to do |format|
        if @main_table.update(model_attributes)
          format.js
        else
          format.js { render :edit }
        end
      end
    end

    # Action Delete
    def delete
      @main_form = 'form_delete'
    end

    # Action Destroy
    def destroy
      @main_table.update(deleted: true, deleted_description: params[@param_model][:deleted_description])
      respond_to do |format|
        format.js
      end
    end
    
    # Private actions
    private
    
    # Important! - Change values according the model
    def set_main_model
      @main_model  =  Profile
      @param_model = :profile
    end

    # Don't change the Order! settings for set_model (second action)
    def set_model
      @main_table = @main_model.find(params[:id])
    end
    
    # Don't change the Order! settings for set_form  (third action)
    def set_main_form
      @main_form = 'form'
    end

    def set_list_collections
      @accesses = Access.all 
    end
    
    # Params for model , this action is always the last don't change the orgder
    def model_attributes
      params.require(@param_model).permit!
    end
  end
end

app/views/admin_management/profiles/partials/_form.html.erb
<%= form_with(model: @main_table, url: @main_table.persisted? ? "#{@main_url}/#{@main_table.id}" : @main_url, method: @main_table.persisted? ? :patch : :post, local: false, html: { id: 'main_form', data: { parsley_validate: true } }) do |form| %>

  <% if @main_table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@main_table.errors.count, "error encontrado:") %></h2>
      <ul>
        <% @main_table.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Nombre:
    <%= form.text_field :name, required: true, data: { parsley_required: "true", parsley_minlength: "3" }, class: "form-control" %>
  </div>

  <div class="field mt-3">
    Accesos
    <% @accesses.group_by(&:resource_name).each do |resource_name, accesses| %>
      <div class="border p-2 mb-2">
        <h5><%= resource_name %></h5>
        <div class="row">
          <% accesses.each_slice(4) do |access_group| %>
            <div class="row mb-2">
              <% access_group.each do |access| %>
                <div class="col-md-3">
                  <div class="form-check">
                    <%= form.check_box :access_ids, { multiple: true, class: 'form-check-input' }, access.id, nil %>
                    <%= form.label "access_ids_#{access.id}", access.full_access_name, class: 'form-check-label' %>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>


  <div class="field mt-3">
    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control", accept: "image/jpeg, image/jpg, image/png" %>
  </div>

  <% if @main_table.persisted? %>
    <div class="form-check mt-3">
      <%= form.check_box :active, class: "form-check-input", id: "activeCheck" %>
      <label class="form-check-label" for="activeCheck">Estado</label>
    </div>
  <% end %> 
  
<% end %>

app/views/admin_management/profiles/partials/_form_delete.html.erb
<%= form_with(model: @main_table, url: "#{@main_url}/#{@main_table.id}" , method: :delete, local: false, html: { id: 'main_form', data: { parsley_validate: true } }) do |form| %>

  <div class="field">
    Nombre:
    <input class="form-control" disabled value="<%= @main_table.name %>"  >
  </div>

  <div class="field mt-3">
    Motivo de eliminación:
    <%= form.text_area :deleted_description, required: true, data: { parsley_required: "true", parsley_minlength: "3" }, class: "form-control" , rows: 3 %>
  </div> 
  
<% end %>

app/views/admin_management/profiles/partials/_form_show.html.erb
<div class="field">
  Nombre:
  <input class="form-control" disabled value="<%= @main_table.name %>"  >
</div>

<div class="field mt-3">
  Accesos:
  <% @main_table.accesses.group_by(&:resource_name).each do |resource_name, accesses| %>
    <div class="border p-2 mb-2">
      <h5><%= resource_name %></h5>
      <div class="row">
        <% accesses.each_slice(4) do |access_group| %>
          <div class="row mb-2">
            <% access_group.each do |access| %>
              <div class="col-md-3">
                <div class="form-check">
                  <input type="checkbox" class="form-check-input" disabled checked>
                  <label class="form-check-label"><%= access.full_access_name %></label>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div class="field mt-3">
  Imagen:
  <% if @main_table.image.attached? %>
    <%= image_tag @main_table.image, class: "img-fluid" %>
  <% else %>
    <p>No hay imagen adjunta</p>
  <% end %>
</div> 

app/views/admin_management/profiles/partials/_modal_div.html.erb
<div class="modal fade" id="main_modal" tabindex="-1" aria-hidden="true" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= @action_title%> <%= @title_modal %></h5>
        <button type="button" class="btn btn-close" data-bs-dismiss="modal" aria-label="Close"><i class="fas fa-times"></i></button>
      </div>
      <div class="modal-body">
        <%= render :partial => @main_url + "/partials/" + @main_form, locals: { main_table: @main_table } %>
      </div>
      <div class="modal-footer">
        <% if show_save_button %>
          <%= button_tag(type: 'submit', class: "btn bg-olive", form: 'main_form') do %>
            <i class="fas fa-save"></i> Guardar
          <% end %>
        <% end %>

        <% if show_delete_button %>
          <%= button_tag(type: 'submit', class: "btn bg-danger", form: 'main_form') do %>
            <i class="fas fa-trash"></i> Eliminar
          <% end %>
        <% end %>

        <%= link_to "", class: "btn btn-secondary btn-close-form", data: { bs_dismiss: "modal" } do %>
          <i class="fas fa-times"></i> Cerrar
        <% end %>  
      </div>         
    </div>
  </div>
</div>

app/views/admin_management/profiles/partials/_table.html.erb
<table class="table table-bordered table-hover" id="main-table">
  <thead>
    <tr>
      <th>Nº</th>
      <th>Nombre</th>
      <th>Imagen</th>      
      <th>Estado</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody id="body-list">
    <%= render partial: @main_url + '/partials/table_body', locals: { list_array: @list_array } %>
  </tbody> 
</table>

<%= render :partial =>"layouts/datatable_plugin" %>

app/views/admin_management/profiles/partials/_table_body.html.erb
<% @list_array.each_with_index do |array,index| %>
<tr id="fila-<%= array.id %>">
  <td><%= index + 1 %></td>

  <td><%= array.name %></td>  
  
  <td>
    <% if array.image.attached? %>
        <%= image_tag array.image, class: "small-img"  %>
    <% else %>
      <p>No hay imagen adjunta</p>
    <% end %>
  </td>

  <td><%= array.active_status %></td>

  <td>
    <% if current_account.has_permission?('show', 'Profile') %>
      <a class="btn bg-info btn-sm" data-remote="true" href="<%= @main_url %>/<%= array.id %>" title="Mostrar">
        <i class="fas fa-eye"></i>  
      </a>
    <% end %>

    <% if current_account.has_permission?('edit', 'Profile') %>
      <a class="btn btn-warning btn-sm text-white" data-remote="true" href="<%= @main_url %>/<%= array.id %>/edit">
        <i class="fas fa-pencil-alt"></i>  
      </a>
    <% end %>

    <% if current_account.has_permission?('delete', 'Profile') %>
      <a class="btn bg-danger btn-sm" data-remote="true" href="<%= @main_url %>/<%= array.id %>/delete">
        <i class="fas fa-trash"></i>  
      </a>
    <% end %>
  </td>
</tr>
<% end %>